DM-33661: narrativelog: initial chart
lsst-sqre/charts pull request #646
Opened 2022-02-11 23:06 UTC by r-owen

2022-02-14 16:49 UTC, athornton submitted a review, later dismissed
Same as for the phalanx PR, ensure that the settings for black/flake8 match what we're doing elsewhere.  Otherwise looks good.  I don't think we've done horizontal pod autoscaling elsewhere, but no reason not to give it a try.

I think we probably want to move the .helmignores up and out of the individual charts, but that's another PR for another time.

2022-02-14 19:23 UTC, jonathansick requested changes
If possible, I'd recommend splitting this PR into two: one for adding narrativelog and one for modifying the chart repo's testing infrastructure.

Was this chart made made with our recommended template (https://github.com/lsst-sqre/charts#adding-a-new-chart-to-this-repository)? It seems like some of the podSecurityContext and securityContext defaults in values aren't being set as well as duplication between imagePullSecrets and pull_secret.

2022-02-14 19:23 UTC, jonathansick commented on charts/narrativelog/Chart.yaml
> +description: Exposure log service
Update for narrative log?

2022-02-14 21:53 UTC, r-owen commented
I moved the linting changes to another ticket. All that's left here should be the narrativelog files.

2022-02-15 19:07 UTC, jonathansick requested changes
I've got some line comments on areas where we want to move to our standardized chart regarding security contexts and ingress. Another thing missing is a NetworkPolicy, which you can get from https://github.com/lsst-sqre/charts/blob/master/rsp-starter/templates/networkpolicy.yaml

2022-02-15 19:07 UTC, jonathansick commented on charts/narrativelog/templates/deployment.yaml
> +            {{- toYaml .Values.securityContext | nindent 12 }}
Also we've started to bake in a securityContext for our containers: https://github.com/lsst-sqre/charts/blob/b37a33f1f0298a0e1e16bf18757655eafbfb0e99/rsp-starter/templates/deployment.yaml#L34-L39

2022-02-15 19:07 UTC, jonathansick commented on charts/narrativelog/templates/ingress.yaml
> +{{- if .Values.ingress.enabled -}}
A more standardized ingress that works well with the Phalanx/RSP auth is https://github.com/lsst-sqre/charts/blob/master/rsp-starter/templates/ingress.yaml

2022-02-15 21:41 UTC, jonathansick commented on charts/narrativelog/templates/ingress.yaml
> +            backend:
Try an extra `{{- end }}` above backend?

See https://github.com/lsst-sqre/charts/blob/b37a33f1f0298a0e1e16bf18757655eafbfb0e99/rsp-starter/templates/ingress.yaml#L30

2022-02-15 21:46 UTC, r-owen commented
All changes made, after fixing an error in the provided ingress file (an extra "end" before "backend").

2022-02-15 21:49 UTC, jonathansick approved these changes
Ok, this looks good. there's there the hold-over `pull_secret` the values.yaml but it's not used.

2022-02-15 21:54 UTC, r-owen commented
Thanks. I removed the extra pull_secret from values.yaml. Now I just need @athornton  to sign off on it.

2022-02-15 22:15 UTC, merged